version: '3.2'

services:
  paperserver:
    image: paperserver:1.0.3
    container_name: 'paperserver'
    ports:
      - 25565:25565
    volumes:
      - "./Volumes/Configuration:/Workspace/Configuration"
      - "./Volumes/Data:/Workspace/Data"
      - "./Volumes/Logs:/Workspace/Logs"
    environment:
      - accept_minecraft_eula=true
      - java_xms=2G
      - java_xmx=4G
