@startuml CodeUnits-Overview
skinparam defaultFontName "DejaVu Sans"
title CodeUnits of PaperServer

[PaperServer]
note as PaperServerNote
  PaperServer is a docker-image for simply running a Paper-server in a docker-container.
end note
PaperServer .. PaperServerNote


@enduml